AllCops:
  DisabledByDefault: true
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/*'
    - 'client/**/*'
    - 'coverage/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'vendor/bundle/**/*'
require:
  - ./lib/cops/useless_only.rb
  - ./lib/cops/callbacks_activerecord.rb
  - ./lib/cops/protected_scope_cop.rb
  - ./lib/cops/regex_cop.rb
  - ./lib/cops/strings_in_activerecords.rb
  - ./lib/cops/rubocop_disable.rb
  - ./lib/cops/rest_only_cop.rb
  - ./lib/cops/uncommented_gem.rb
  - ./lib/cops/keyword_defaults.rb
  - ./lib/cops/params_passing.rb

Ducalis/CallbacksActiverecord:
  Enabled: true

Ducalis/ProtectedScopeCop:
  Enabled: true

Ducalis/RegexCop:
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'

Ducalis/StringsInActiverecords:
  Enabled: true

Ducalis/UselessOnly:
  Enabled: true

Ducalis/RestOnlyCop:
  Enabled: true

Ducalis/KeywordDefaults:
  Enabled: true

Ducalis/RubocopDisable:
  Enabled: true

Ducalis/UncommentedGem:
  Enabled: true
  Include:
    - '**/Gemfile'
    - '**/gems.rb'

Ducalis/ParamsPassing:
  Enabled: true
