AllCops:
  TargetRubyVersion: 2.4
  UseCache: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
Lint/InterpolationCheck:
  Exclude:
    - 'spec/**/*.rb'
Style/Documentation:
  Enabled: false
