AllCops:
  TargetRubyVersion: 2.1
  UseCache: false
  Exclude:
    - 'client/vendor/bundle/**/*'
    - 'vendor/bundle/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
Style/Documentation:
  Enabled: false
