AllCops:
  DisabledByDefault: true
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'vendor/bundle/**/*'

Ducalis/BlackListSuffix:
  Enabled: true
  BlackList:
    - Sorter
    - Manager
    - Client
    - Object
    - Handler
    - Processor
    - Organizer
    - Analyzer
    - Renderer
    - Loader

Ducalis/PreferableMethods:
  Enabled: true

Ducalis/CaseMapping:
  Enabled: true

Ducalis/CallbacksActiverecord:
  Enabled: true

Ducalis/PossibleTap:
  Enabled: true

Ducalis/ProtectedScopeCop:
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'
    - 'app/workers/**/*.rb'
    - 'app/mailers/**/*.rb'

Ducalis/RegexCop:
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'

Ducalis/StringsInActiverecords:
  Enabled: true

Ducalis/TooLongWorkers:
  Enabled: true
  Max: 25

Ducalis/UselessOnly:
  Enabled: true

Ducalis/RestOnlyCop:
  Enabled: true

Ducalis/KeywordDefaults:
  Enabled: true

Ducalis/RubocopDisable:
  Enabled: true

Ducalis/UncommentedGem:
  Enabled: true
  Include:
    - '**/Gemfile'
    - '**/gems.rb'

Ducalis/ParamsPassing:
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'

Ducalis/ControllersExcept:
  Enabled: true

Ducalis/PrivateInstanceAssign:
  Enabled: true

Ducalis/RaiseWithoutErrorClass:
  Enabled: true

Ducalis/ModuleLikeClass:
  Enabled: true
  AllowedIncludes:
    - Sidekiq::Worker
    - Singleton
    - ActiveModel::Model
