AllCops:
  DisabledByDefault: true
  TargetRubyVersion: 2.4
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/bundle/**/*'

Ducalis/CallbacksActiverecord:
  Enabled: true

Ducalis/ProtectedScopeCop:
  Enabled: true

Ducalis/RegexCop:
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'

Ducalis/StringsInActiverecords:
  Enabled: true

Ducalis/UselessOnly:
  Enabled: true

Ducalis/RestOnlyCop:
  Enabled: true

Ducalis/KeywordDefaults:
  Enabled: true

Ducalis/RubocopDisable:
  Enabled: true

Ducalis/UncommentedGem:
  Enabled: true
  Include:
    - '**/Gemfile'
    - '**/gems.rb'

Ducalis/ParamsPassing:
  Enabled: true

Ducalis/ControllersExcept:
  Enabled: true

Ducalis/PrivateInstanceAssign:
  Enabled: true

Ducalis/RaiseWithourErrorClass:
  Enabled: true

Ducalis/ModuleLikeClass:
  Enabled: true
  AllowedIncludes:
    - Sidekiq::Worker
    - Singleton
    - ActiveModel::Model
