AllCops:
  DisabledByDefault: true
  TargetRubyVersion: ~
  Exclude:
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'vendor/bundle/**/*'

Ducalis/BlackListSuffix:
  Enabled: true
  BlackList:
    - Analyzer
    - Client
    - Handler
    - Loader
    - Manager
    - Object
    - Organizer
    - Processor
    - Renderer
    - Service
    - Sorter

Ducalis/EnforceNamespace:
  Enabled: true
  ServicePath: 'app/services'

Ducalis/PreferableMethods:
  Enabled: true

Ducalis/Recursion:
  Enabled: true

Ducalis/ComplexRegex:
  Enabled: true
  MaxComplexity: 3

Ducalis/CaseMapping:
  Enabled: true

Ducalis/FacadePattern:
  Enabled: true
  MaxInstanceVariables: 4

Ducalis/CallbacksActiverecord:
  Enabled: true

Ducalis/DataAccessObjects:
  Enabled: true

Ducalis/PossibleTap:
  Enabled: false

Ducalis/PublicSend:
  Enabled: true

Ducalis/FetchExpression:
  Enabled: true

Ducalis/ProtectedScopeCop:
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'
    - 'app/workers/**/*.rb'
    - 'app/mailers/**/*.rb'

Ducalis/RegexCop:
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'

Ducalis/StringsInActiverecords:
  Enabled: true

Ducalis/TooLongWorkers:
  Enabled: true
  Max: 25

Ducalis/OnlyDefs:
  Enabled: true

Ducalis/UselessOnly:
  Enabled: true

Ducalis/RestOnlyCop:
  Enabled: true

Ducalis/KeywordDefaults:
  Enabled: true

Ducalis/MultipleTimes:
  Enabled: true

Ducalis/OptionsArgument:
  Enabled: true

Ducalis/RubocopDisable:
  Enabled: true

Ducalis/UncommentedGem:
  Enabled: true
  Include:
    - '**/Gemfile'
    - '**/gems.rb'

Ducalis/ParamsPassing:
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'

Ducalis/ControllersExcept:
  Enabled: true

Ducalis/PrivateInstanceAssign:
  Enabled: true

Ducalis/EvlisOverusing:
  Enabled: true

Ducalis/StandardMethods:
  Enabled: true

Ducalis/RaiseWithoutErrorClass:
  Enabled: true

Ducalis/UnlockedGem:
  Enabled: true

Ducalis/ModuleLikeClass:
  Enabled: true
  AllowedIncludes:
    - Sidekiq::Worker
    - Singleton
    - ActiveModel::Model
    - Virtus.model

Ducalis/DescriptiveBlockNames:
  Enabled: true
  MinimalLenght: 3
  WhiteList:
    - to
    - id
